from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = '4e636a3721fc'
down_revision: Union[str, Sequence[str], None] = '9bc5be3861e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get the database connection and inspector
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)

    # Check if the 'products' table exists before creating it
    if 'products' not in inspector.get_table_names():
        op.create_table('products',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('name', sa.String(length=40), nullable=False),
                        sa.Column('description', sa.String(), nullable=False),
                        sa.Column('price', sa.Integer(), nullable=False),
                        sa.Column('image', sa.String(length=255), nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.PrimaryKeyConstraint('id')
                        )

    # Check if the 'orders' table exists before creating it
    if 'orders' not in inspector.get_table_names():
        op.create_table('orders',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('user_id', sa.Integer(), nullable=False),
                        sa.Column('total_amount', sa.Integer(), nullable=False),
                        sa.Column('created_at', sa.DateTime(), nullable=False),
                        sa.Column('status', sa.String(length=50), nullable=False),
                        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                        sa.PrimaryKeyConstraint('id')
                        )

    # Add columns to carts table if they don't already exist
    if 'product_id' not in [col['name'] for col in inspector.get_columns('carts')]:
        op.add_column('carts', sa.Column('product_id', sa.Integer(), nullable=False))

    if 'quantity' not in [col['name'] for col in inspector.get_columns('carts')]:
        op.add_column('carts', sa.Column('quantity', sa.Integer(), nullable=False))

    if 'created_at' not in [col['name'] for col in inspector.get_columns('carts')]:
        op.add_column('carts', sa.Column('created_at', sa.DateTime(), nullable=False))

    # Use batch mode for SQLite to handle foreign key creation
    if bind.dialect.name == 'sqlite':
        with op.batch_alter_table('carts') as batch_op:
            batch_op.create_foreign_key('fk_product_id', 'products', ['product_id'], ['id'])
    else:
        op.create_foreign_key(None, 'carts', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        with op.batch_alter_table('carts') as batch_op:
            batch_op.drop_constraint('fk_product_id')

    op.drop_column('carts', 'created_at')
    op.drop_column('carts', 'quantity')
    op.drop_column('carts', 'product_id')
    op.drop_table('orders')
    op.drop_table('products')
    # ### end Alembic commands ###
